version: '3.7'

services:
  sample:
    container_name: sample-react-app-backend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 8083:8083
    environment:
      - CHOKIDAR_USEPOLLING=true